baseURL = "https://pascaljorratt.github.io/"
locale = "es-CL"
title = "Blog de análisis y opinión"
theme = "not-much"
defaultContentLanguage = "es"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[params]
  theme = "auto"
  palette = "eink"
  showThemeNotice = true
  showPostsSummary = true

[languages]
[languages.es]
languageName = "Español"
contentDir = "content/es"
weight = 1

[[languages.es.menu.main]]
identifier = "home"
name = "Inicio"
url = "/"
weight = 1

[[languages.es.menu.main]]
identifier = "about"
name = "Sobre mí"
url = "/about"
weight = 2

[[languages.es.menu.main]]
identifier = "posts"
name = "Publicaciones"
url = "/posts"
weight = 3

[[languages.es.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 4

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 2

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/en/"
weight = 1

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/en/about"
weight = 2

[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/en/posts"
weight = 3

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/en/tags"
weight = 4
